'use client';

import React from 'react';
import Link from 'next/link';
import { 
  RefreshCw, 
  Recycle, 
  Zap, 
  ArrowRight, 
  Sparkles, 
  Leaf, 
  ShieldCheck, 
  Layers,
  CheckCircle2,
  Cpu
} from 'lucide-react';
import { useReVoltX } from '../../lib/store/batteryStore';
import { BatteryStatusBadge } from '../../components/ui/BatteryStatusBadge';
import MagicBento, { MagicBentoCardItem } from '../../components/ui/MagicBento';

export default function CircularityDashboardPage() {
  const { opportunities, recyclingRecords, batteries } = useReVoltX();

  const circularityBentoCards: MagicBentoCardItem[] = [
    {
      label: 'CERTIFIED INVENTORY',
      title: 'Available 2nd-Life Packs',
      value: '174 Packs',
      sub: 'Certified for Stationary Duty',
      description: 'Retired mobility packs screened by automated impedance testing for ESS, telecom & microgrid deployment.',
      badge: <span className="text-[10px] font-mono px-2 py-0.5 rounded-full bg-blue-500/10 text-[#0070F3] border border-blue-500/20 font-bold">Ready</span>
    },
    {
      label: 'ENERGY RESERVE',
      title: 'Potential Storage Capacity',
      value: '14.2 MWh',
      sub: 'Stationary Buffer Pool',
      description: 'Total cumulative second-life capacity available for peak shaving and renewable solar grid buffering.',
      badge: <span className="text-[10px] font-mono px-2 py-0.5 rounded-full bg-blue-500/10 text-[#0070F3] border border-blue-500/20 font-bold">14,200 kWh</span>
    },
    {
      label: 'QUALIFICATION DOCK',
      title: 'Second-Life Candidates',
      value: '48 Pending',
      sub: 'Completing Smart Dock Tests',
      description: 'Incoming packs undergoing automated electrochemical impedance spectroscopy and cell balance validation.',
      badge: <span className="text-[10px] font-mono px-2 py-0.5 rounded-full bg-sky-500/10 text-sky-400 border border-sky-500/20 font-bold">In Testing</span>
    },
    {
      label: 'RESOURCE RECOVERY',
      title: 'Recycling Candidates',
      value: '26 Packs',
      sub: 'SOH < 50% End of Life',
      description: 'Severely degraded packs routed to automated mechanical shredding and hydrometallurgical leaching.',
      badge: <span className="text-[10px] font-mono px-2 py-0.5 rounded-full bg-red-500/10 text-red-500 border border-red-500/20 font-bold">Recycler Hub</span>
    },
    {
      label: 'MINERAL PURITY',
      title: 'Material Recovery Yield',
      value: '96.4% Li/Ni',
      sub: 'Purified Black Mass Grade',
      description: 'Closed-loop extraction recovering battery-grade lithium carbonate, nickel sulfate, and cobalt.',
      badge: <span className="text-[10px] font-mono px-2 py-0.5 rounded-full bg-blue-500/10 text-[#0070F3] border border-blue-500/20 font-bold">Certified 99.8%</span>
    },
    {
      label: 'CIRCULAR IMPACT',
      title: 'Lifecycle Decarbonization',
      value: '1,280 tCO2e',
      sub: 'Avoided Raw Mining Emissions',
      description: 'Verified carbon reduction credits generated by extending pack operational lifetime by 8-10 years.',
      badge: <span className="text-[10px] font-mono px-2 py-0.5 rounded-full bg-blue-500/10 text-[#0070F3] border border-blue-500/20 font-bold">ESG Gold</span>
    }
  ];

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b border-[#DDE7E2]">
        <div>
          <div className="flex items-center gap-2">
            <span className="text-xs font-bold uppercase tracking-wider text-[#0284C7] bg-[#F0F9FF] px-2.5 py-0.5 rounded-full border border-[#BAE6FD]">
              Circularity Partner Network
            </span>
            <span className="text-[11px] text-[#62756E]">
              Stationary Storage • Telecom • Hydrometallurgical Recyclers
            </span>
          </div>
          <h1 className="text-2xl font-bold text-[#10201B] mt-1.5">
            Second-Life & Resource Recovery Intelligence
          </h1>
          <p className="text-xs text-[#62756E]">
            Discover qualified retired mobility batteries and allocate raw critical minerals.
          </p>
        </div>

        <div className="flex items-center gap-2">
          <Link
            href="/circularity/opportunities"
            className="inline-flex items-center gap-1.5 px-4 py-2 rounded-xl bg-[#0070F3] text-white text-xs font-bold hover:bg-[#0058C6] shadow-xs transition-colors"
          >
            <Sparkles className="w-3.5 h-3.5" />
            <span>Browse Opportunities</span>
          </Link>
          <Link
            href="/circularity/recycling"
            className="inline-flex items-center gap-1.5 px-4 py-2 rounded-xl bg-white text-[#10201B] text-xs font-semibold hover:bg-[#F0F5F2] border border-[#DDE7E2] transition-colors"
          >
            <Recycle className="w-3.5 h-3.5 text-[#D94B4B]" />
            <span>Recycler Hub</span>
          </Link>
        </div>
      </div>

      {/* Interactive Circularity Magic Bento */}
      <MagicBento 
        cards={circularityBentoCards}
        textAutoHide={false}
        enableStars={true}
        enableSpotlight={true}
        enableBorderGlow={true}
        enableTilt={true}
        enableMagnetism={true}
        clickEffect={true}
        spotlightRadius={320}
        particleCount={14}
        glowColor="0, 112, 243"
      />

      {/* Recommended Opportunities List */}
      <div className="bg-white rounded-3xl p-6 border border-[#DDE7E2] shadow-xs space-y-4">
        <div className="flex items-center justify-between">
          <div>
            <h3 className="text-base font-bold text-[#10201B]">
              Recommended Second-Life Opportunities
            </h3>
            <p className="text-xs text-[#62756E]">
              Ranked by electrochemical compatibility and target application suitability.
            </p>
          </div>

          <Link
            href="/circularity/opportunities"
            className="text-xs font-semibold text-[#0070F3] hover:underline flex items-center gap-1"
          >
            <span>View All Opportunities</span>
            <ArrowRight className="w-3.5 h-3.5" />
          </Link>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          {opportunities.map(opp => (
            <div
              key={opp.id}
              className="p-5 rounded-2xl bg-[#F7FAF8] border border-[#DDE7E2] flex flex-col justify-between hover:border-[#0070F3] transition-colors"
            >
              <div>
                <div className="flex items-center justify-between mb-2">
                  <span className="font-mono font-bold text-xs text-[#10201B]">
                    {opp.batteryId}
                  </span>
                  <span className={`px-2 py-0.5 rounded-full text-[10px] font-bold ${
                    opp.status === 'Available' ? 'bg-[#EFF6FF] text-[#0070F3]' : 'bg-[#F0F5F2] text-[#62756E]'
                  }`}>
                    {opp.status}
                  </span>
                </div>

                <h4 className="text-xs font-bold text-[#10201B]">{opp.title}</h4>
                <p className="text-[11px] text-[#62756E] mt-1">
                  Target: <strong className="text-[#10201B]">{opp.targetApplication}</strong>
                </p>

                <div className="mt-3 grid grid-cols-2 gap-2 text-[11px] p-2 bg-white rounded-xl border border-[#DDE7E2]">
                  <div>
                    <span className="text-[#62756E] text-[10px]">Capacity:</span>
                    <p className="font-bold font-mono text-[#10201B]">{opp.capacityKWh} kWh</p>
                  </div>
                  <div>
                    <span className="text-[#62756E] text-[10px]">SOH:</span>
                    <p className="font-bold font-mono text-[#0070F3]">{opp.soh}%</p>
                  </div>
                </div>
              </div>

              <div className="mt-4 pt-3 border-t border-[#DDE7E2] flex items-center justify-between">
                <span className="font-mono font-bold text-xs text-[#10201B]">
                  ${opp.economicValueUsd}
                </span>

                <Link
                  href={`/circularity/opportunities/${opp.batteryId}`}
                  className="inline-flex items-center gap-1 text-xs font-bold text-[#0070F3] hover:underline"
                >
                  <span>Inspect & Claim</span>
                  <ArrowRight className="w-3.5 h-3.5" />
                </Link>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
